version: '3.8'

services:
  frontend:
    build:
      context: ./digital-twin-car-dashboard
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - MQTT_BROKER=mqtt
    depends_on:
      - mqtt
      - backend

  backend:
    build:
      context: ./digital_twin_logic/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MQTT_BROKER=mqtt
      - MQTT_PORT=1883
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    depends_on:
      - mqtt

  mqtt:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./digital_twin_logic/mosquitto/config:/mosquitto/config
      - ./digital_twin_logic/mosquitto/data:/mosquitto/data
      - ./digital_twin_logic/mosquitto/log:/mosquitto/log